### ISSUE TITLE
Do not start smoothing until the first non-zero datapoint

### ISSUE THREAD

**Issue by gregdan3** [gregdan3/ilo-muni#12]
There is currently an issue with smoothing where a misleading graph is produced when smoothing is set but the graphed period begins before a given term was ever used. [misikeke](https://gregdan3.github.io/ilo-muni/?query=misikeke&minSentLen=1&scale=rel&start=1470009600&end=1722470400&smoothing=0)

This change would at least guarantee that the graph wouldn't show anything but zero until the first real datapoint appears.

Things I'm unsure of:
- Should I average with the prior zeroes, or treat the first found point as the start of the array? Currently, I have a preference for the former, since it would create a smooth upward curve.
- What about data where a single occurrence exists in the middle of a sea of zeroes, like [asiku](https://gregdan3.github.io/ilo-muni/?query=asiku&minSentLen=1&scale=rel&start=1627776000&end=1722470400&smoothing=0)?

**Comment by SarahIsWeird** [comment]
I did some experimentation, and [exponential smoothing](https://en.wikipedia.org/wiki/Exponential_smoothing) seems to work pretty well for this kind of stuff, as it handles data points being zero gracefully.

misikeke with 50 smoothing applied:
![Graph showing the relative usage of misikeke with exponential smoothing 50 applied](https://github.com/user-attachments/assets/f9128cc8-77ca-4522-91c4-df0926fd0019)

asiku also works more or less as expected, since the window is so huge it doesn't go back to zero, but it seems to be way better.

![Graph showing the relative usage of asiku with exponential smoothing 50 applied](https://github.com/user-attachments/assets/b1dc0001-5b41-4939-9dac-4a9980d7ac92)

One thing is that exponential smoothing can't be used to predict any future trends, as per Wikipedia. Is that something that's desired? If so, might wanna look into other kinds of smoothers. If it's just to pick out trends in the *past*, it seems suitable enough.

I've also tried additive smoothing, but it *cannot* work for this data, as usages for words like misikeke are in the decimals, and any smoothing factor applied greatly skews the data. (Also, it doesn't fix the issue of zeroes anyways.)

Lmk what you think about it! Implementation is a dead-simple three-liner:
```ts
const alpha = 1 / (smoothing + 1);
for (let i = 1; i < rows.length; i++) {
    smoothed[i].occurrences = alpha * rows[i].occurrences + (1 - alpha) * smoothed[i - 1].occurrences;
}
```

Had a play with it and it seems to be p cool. If you want, I can create a PR.

**Comment by SarahIsWeird** [comment]
One thing it does not do, which the current smoothing doesn't do either, is preserve the scale. Smoothing `mu` makes the maximum relative occurrence drop from about 0.02 to 0.0045. The current smoothing behaves similarly, however, with the same query resulting in a comparable drop from about 0.02 to 0.006. Fwiw smoothed scales can be a bit weird anyways, but it's something to look out for, and definitely worth a note somewhere in the application if left untreated.

**Comment by SarahIsWeird** [comment]
Oh, and just for reference, this is the current smoothing applied to the examples given above:

misikeke
![image](https://github.com/user-attachments/assets/7a054e3e-45fd-4b03-ad6d-d50746f46623)

and asiku
![image](https://github.com/user-attachments/assets/13c2cdc1-1163-4b57-b026-409f6bdd5c8e)

**Comment by gregdan3** [comment]
This is interesting! I think an alternate smoothing method could be an option unto itself, which should probably be explored separately from this. Although, granted, that's both an incredibly low importance thing and creates more complexity for users... Ehe. Probably best to pick one which is most apt.

As a point of reference, my smoothing implementation is copied from how Google described theirs [here](https://books.google.com/ngrams/info): 

> Often trends become more apparent when data is viewed as a moving average. A smoothing of 1 means that the data shown for 1950 will be an average of the raw count for 1950 plus 1 value on either side: ("count for 1949" + "count for 1950" + "count for 1951"), divided by 3. So a smoothing of 10 means that 21 values will be averaged: 10 on either side, plus the target value in the center of them. 

Turns out this is called the "centered moving average." Aside from the fact that, normally, the smoothing also involves cutting off the members of the series which did not have a full window to smooth with- Google and Muni both simply average fewer values and deal with that point of misleading-ness.

Something that may be worth exploring is the ["Friedman super smoother"](https://www.slac.stanford.edu/cgi-bin/getdoc/slac-pub-3477.pdf), since it reportedly can find localized windows to average over- ideally, preserving trend lines. Presumably, it would also not exhibit the back-averaging error in the current implementation.

> One thing it does not do, which the current smoothing doesn't do either, is preserve the scale

Yep, this is something I realized post-release: the selectable scales immediately rewrite the data in ChartJS, including its scale- the original scale derived from the unsmoothed data should be used! I don't think this would be hard to do, I just didn't think about it before release. 
On a related note, the logarithm scales are misleading- they show the actual logarithm, rather than altering chartJS's Y axis to be logarithmic.

> One thing is that exponential smoothing can't be used to predict any future trends, as per Wikipedia. Is that something that's desired? If so, might wanna look into other kinds of smoothers. If it's just to pick out trends in the past, it seems suitable enough.

Honestly, if people *don't* try to use Muni to predict future trends, that might be better? Ehe. 

Will test this out with a few sample graphs tomorrow, and maybe try implementing the super smoother as well!

**Comment by gregdan3** [comment]
- Window average is now the default again, instead of exponential
- I added some logic to the center window average function to skip past leading zero elements in the data for cwin
- It looks fine up to 10 smoothing, but more than that gets really silly
- It might be appropriate to do the same for the other smoothers (exponential does not need it), unsure

![image](https://github.com/user-attachments/assets/22f21138-3900-4042-8138-f963fcbe2d2e)


![image](https://github.com/user-attachments/assets/1d42c3b6-db52-4070-a309-21a1e2170f10)

(weko is just a random thing i guessed would exist)
