### ISSUE TITLE
Doesn't support Emoji

### ISSUE THREAD

**Issue by gtbot2007** [gregdan3/ilo-muni#18]
Doesn't support Emoji. I know emoji support would be clunky because most of the data is from discord which has its own custom emojis, but I still think it would be neat to support emojis.

**Comment by gregdan3** [comment]
I'd like to outline the challenges in doing this to explain why I don't expect to support this any time soon, or really ever. 

Tokenization around emojis is absurdly difficult. When processing a message to be counted for frequentcy, [I explicitly exclude several objects which are difficult to tokenize](https://github.com/gregdan3/sona-toki/blob/a3cd51a7b48d306fcb21b4cdf84a0799cf3e7d9b/src/sonatoki/Configs.py#L97)- Emoji, codeblocks, URLs, Discord's emotes and mentions, and \[\[references\]\]. Each of these is relatively easy to detect in a stream of characters via regex, but are unreasonable to detect after tokenization. My tokenizer assumes that all tokens can be divided into word-candidates (contiguous writing characters) and non-candidates (contiguous "punctuation"). Granted, I did add an exception for some kinds of intra-word punctuation, but that was very specific and small in scope. Emoji "punctuation" is nightmarish. 

- [Variation selectors](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) break a core assumption of my tokenizer, because they are considered a non-spacing mark according to [Unicode's character classification](https://unicode.org/Public/UNIDATA/UnicodeData.txt), which means it is inherited into the `\p{Punct}` regex character class. But they follow the character they correspond to, rather than being between other characters. This makes sense for the character, but makes them hard to deliver accurately.
- Zero width space is also considered punctuation, insofar as being a format character.
- [Regional Indicators](https://en.wikipedia.org/wiki/Regional_indicator_symbol), by definition, don't have any joiners and don't necessarily have a single representation.

I can do some experiments with including these characters as writing characters, since they don't generally appear with toki pona's latin script, but that still isn't a near-future thing. I have higher priorities for now.
